before_script:

  # Replace a hardcoded version string with a Gitlab build ID
  - sed -i "s/CI_PIPELINE_ID/$CI_PIPELINE_ID/g" pom.xml

stages:
  - deploy

"Generate jar and deploy to maven repo":
  stage: deploy
  only:
    - tags
  script:
    - make clean compile package deploy
